# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BorsdataMcp < Formula
  desc "MCP server for Börsdata API"
  homepage "https://github.com/emmanuelay/borsdata-mcp"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/emmanuelay/borsdata-mcp/releases/download/v0.0.1/borsdata-mcp_0.0.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "a89688aa383a494c39058d0873a10e8b497d05a08f0493032158b1d08f2ef114"

      define_method(:install) do
        bin.install "borsdata-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/emmanuelay/borsdata-mcp/releases/download/v0.0.1/borsdata-mcp_0.0.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d6635c3c5f299839d76b57d3bc909c7d98c451e19222adfe2576b4e84079fd01"

      define_method(:install) do
        bin.install "borsdata-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/emmanuelay/borsdata-mcp/releases/download/v0.0.1/borsdata-mcp_0.0.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "fb07d79f0046ef102df7b2e75dc082040d43cb71ba56705fe79b4652b883cb47"
      define_method(:install) do
        bin.install "borsdata-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/emmanuelay/borsdata-mcp/releases/download/v0.0.1/borsdata-mcp_0.0.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d7188d6e9dbca50eb6c4ba76823c5a35923d7b780bbb8b88d8f3df13043ae0cf"
      define_method(:install) do
        bin.install "borsdata-mcp"
      end
    end
  end
end
