# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BorsdataMcp < Formula
  desc "MCP server for Börsdata API"
  homepage "https://github.com/emmanuelay/borsdata-mcp"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/emmanuelay/borsdata-mcp/releases/download/v0.0.1/borsdata-mcp_0.0.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "107619b302ad7c890db436c3e29bbae6b5c38b8d6ba64f5bf93af85c1d808b50"

      define_method(:install) do
        bin.install "borsdata-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/emmanuelay/borsdata-mcp/releases/download/v0.0.1/borsdata-mcp_0.0.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "5f2cd6ef587e870540668363ff4d0afebae4ef7038e40452e114ce83c0d7fa7f"

      define_method(:install) do
        bin.install "borsdata-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/emmanuelay/borsdata-mcp/releases/download/v0.0.1/borsdata-mcp_0.0.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "6e16c1955d3b2c46f54cd2ea269ad908913830f89940cbdf08c6835fae7933c1"
      define_method(:install) do
        bin.install "borsdata-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/emmanuelay/borsdata-mcp/releases/download/v0.0.1/borsdata-mcp_0.0.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "333bec457b4eb90f054c963748c8aeae2af925067b190e3a0c0d02b379b62c11"
      define_method(:install) do
        bin.install "borsdata-mcp"
      end
    end
  end
end
