# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BorsdataMcp < Formula
  desc "MCP server for Börsdata API"
  homepage "https://github.com/emmanuelay/borsdata-mcp"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/emmanuelay/borsdata-mcp/releases/download/v0.0.1/borsdata-mcp_0.0.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "cb60d4301e8f2c70f20531e19323dfa9258f310c614af2e1cb20f98ece56f091"

      define_method(:install) do
        bin.install "borsdata-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/emmanuelay/borsdata-mcp/releases/download/v0.0.1/borsdata-mcp_0.0.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "71b071ac2031dc083f8735090d186603e48e37bcca5713e3d089d0ffd69d0ccc"

      define_method(:install) do
        bin.install "borsdata-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/emmanuelay/borsdata-mcp/releases/download/v0.0.1/borsdata-mcp_0.0.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "5188ddcc77a4323b8d34184eb64c4135484104ca855eb121e005be84d66da8e4"
      define_method(:install) do
        bin.install "borsdata-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/emmanuelay/borsdata-mcp/releases/download/v0.0.1/borsdata-mcp_0.0.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "2c136d87df395d986f9aa58c19f0e128d2c045bd2ea8ce1e349c2a91a1b2451b"
      define_method(:install) do
        bin.install "borsdata-mcp"
      end
    end
  end
end
