# This file was generated by GoReleaser. DO NOT EDIT.
cask "domainbadger" do
  name "domainbadger"
  desc "CLI tool for domain information lookup"
  homepage "https://github.com/emmanuelay/domainbadger"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "domainbadger"

  on_macos do
    on_intel do
      url "https://github.com/emmanuelay/domainbadger/releases/download/v#{version}/domainbadger_#{version}_darwin_amd64.tar.gz"
      sha256 "4681a28435e67d6b3e99eb36d8e6fcf142d9686f05e9b721b1b6b03e89ea0388"
    end
    on_arm do
      url "https://github.com/emmanuelay/domainbadger/releases/download/v#{version}/domainbadger_#{version}_darwin_arm64.tar.gz"
      sha256 "1971da386289009782784bf4a22a94d6c68349c29d0c2be47ed5fb366953485d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/emmanuelay/domainbadger/releases/download/v#{version}/domainbadger_#{version}_linux_amd64.tar.gz"
      sha256 "0846af14af2a8b08db5b4895170472770ffcc29e117c33c71f7865842e7f2d28"
    end
    on_arm do
      url "https://github.com/emmanuelay/domainbadger/releases/download/v#{version}/domainbadger_#{version}_linux_arm64.tar.gz"
      sha256 "2af51c5702283eb3a207f04fc3e64924ebb1789e0523f8a2b291ad645c8109ac"
    end
  end

  # No zap stanza required
end
