# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YahooFinanceMcp < Formula
  desc "MCP server for Yahoo Finance data"
  homepage "https://github.com/emmanuelay/yahoo-finance-mcp"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/emmanuelay/yahoo-finance-mcp/releases/download/v0.0.2/yahoo-finance-mcp_0.0.2_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "c28007f893e939e4108f73d21ff7e2f82a7384d33276eda2c17a6e0293afb742"

      define_method(:install) do
        bin.install "yahoo-finance-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/emmanuelay/yahoo-finance-mcp/releases/download/v0.0.2/yahoo-finance-mcp_0.0.2_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "049027c746252187ba0bed0422bbcb5c44723946444f6c354d44a9240a2bec05"

      define_method(:install) do
        bin.install "yahoo-finance-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/emmanuelay/yahoo-finance-mcp/releases/download/v0.0.2/yahoo-finance-mcp_0.0.2_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "b23c9be2ba89f6c0ff0eda44abc6a9ceae33941376e799a83ef28bf782348285"
      define_method(:install) do
        bin.install "yahoo-finance-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/emmanuelay/yahoo-finance-mcp/releases/download/v0.0.2/yahoo-finance-mcp_0.0.2_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "8c3d42be238b8aebaad6a996c4b276161a791618f6d20082f349db924f02374d"
      define_method(:install) do
        bin.install "yahoo-finance-mcp"
      end
    end
  end
end
