# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class YahooFinanceMcp < Formula
  desc "MCP server for Yahoo Finance data"
  homepage "https://github.com/emmanuelay/yahoo-finance-mcp"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/emmanuelay/yahoo-finance-mcp/releases/download/v0.0.1/yahoo-finance-mcp_0.0.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "287f20561fc4adb8afb7e77f4a360119ddcecb8c40ecdf319eeb2acdd1492317"

      def install
        bin.install "yahoo-finance-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/emmanuelay/yahoo-finance-mcp/releases/download/v0.0.1/yahoo-finance-mcp_0.0.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "180d7afe06bf96902ee4097e90915cfc3ae63824407caf3a6d2c327af22dbc74"

      def install
        bin.install "yahoo-finance-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/emmanuelay/yahoo-finance-mcp/releases/download/v0.0.1/yahoo-finance-mcp_0.0.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "8489b47f5407c6c2fbea9d5aaeb7b74c952c4524fbf0eed7e7ed04900d4e70ab"
      def install
        bin.install "yahoo-finance-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/emmanuelay/yahoo-finance-mcp/releases/download/v0.0.1/yahoo-finance-mcp_0.0.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "4bb323d93156d3ce9f48586ad83f4d9a9fa5023baa01ce0a38f61bbcd274e43a"
      def install
        bin.install "yahoo-finance-mcp"
      end
    end
  end
end
